from marshmallow import Schema, fields


class MosqueSuggestionCreateSchema(Schema):
    arabic_name = fields.Str(load_default=None)
    type = fields.Str(load_default=None)
    governorate = fields.Str(required=True)
    delegation = fields.Str(load_default=None)
    city = fields.Str(load_default=None)
    address = fields.Str(load_default=None)
    latitude = fields.Float(load_default=None)
    longitude = fields.Float(load_default=None)
    image_url = fields.Str(load_default=None)
    facilities = fields.Dict(keys=fields.Str(), values=fields.Boolean(), load_default=dict)
    iqama_times = fields.Dict(keys=fields.Str(), values=fields.Str(), load_default=dict)
    jumuah_time = fields.Str(load_default=None)
    eid_info = fields.Str(load_default=None)
    muazzin_name = fields.Str(load_default=None)
    imam_5_prayers_name = fields.Str(load_default=None)
    imam_jumua_name = fields.Str(load_default=None)


class MosqueSuggestionSchema(Schema):
    id = fields.Int(dump_only=True)
    arabic_name = fields.Str(allow_none=True)
    type = fields.Str(allow_none=True)
    governorate = fields.Str()
    delegation = fields.Str(allow_none=True)
    city = fields.Str(allow_none=True)
    address = fields.Str(allow_none=True)
    latitude = fields.Float(allow_none=True)
    longitude = fields.Float(allow_none=True)
    image_url = fields.Str(allow_none=True)
    facilities = fields.Dict(keys=fields.Str(), values=fields.Boolean(), attribute="facilities_json")
    iqama_times = fields.Dict(keys=fields.Str(), values=fields.Str(), attribute="iqama_times_json")
    jumuah_time = fields.Str(allow_none=True)
    eid_info = fields.Str(allow_none=True)
    muazzin_name = fields.Str(allow_none=True)
    imam_5_prayers_name = fields.Str(allow_none=True)
    imam_jumua_name = fields.Str(allow_none=True)
    status = fields.Str()
    confirmations_count = fields.Int()
    created_at = fields.DateTime()
    updated_at = fields.DateTime()
