"""suggestion jumuah/eid + iqama confirm count

Revision ID: 707d26a692c4
Revises: fa02001ca36a
Create Date: 2026-01-08 09:40:03.336699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '707d26a692c4'
down_revision = 'fa02001ca36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iqama_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iqama_confirmations_iqama_id'))

    op.drop_table('iqama_confirmations')
    with op.batch_alter_table('iqama_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iqama_suggestions_mosque_id'))

    op.drop_table('iqama_suggestions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iqama_suggestions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mosque_id', sa.INTEGER(), nullable=False),
    sa.Column('times_json', sqlite.JSON(), nullable=True),
    sa.Column('jumuah_time', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('confirmations_count', sa.INTEGER(), nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iqama_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iqama_suggestions_mosque_id'), ['mosque_id'], unique=False)

    op.create_table('iqama_confirmations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('iqama_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['iqama_id'], ['iqama_suggestions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iqama_id', 'user_id', name=op.f('uq_iqama_user'))
    )
    with op.batch_alter_table('iqama_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iqama_confirmations_iqama_id'), ['iqama_id'], unique=False)

    # ### end Alembic commands ###
