"""Add staff fields remove neighborhood

Revision ID: c7d0d6f2893e
Revises: d1b2f3a4
Create Date: 2026-01-15 04:46:14.286088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d0d6f2893e'
down_revision = 'd1b2f3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mosque_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iqama_times_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('muazzin_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('imam_5_prayers_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('imam_jumua_name', sa.String(length=120), nullable=True))
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('facilities_details')

    with op.batch_alter_table('mosques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eid_prayer_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('muazzin_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('imam_5_prayers_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('imam_jumua_name', sa.String(length=120), nullable=True))
        batch_op.drop_column('facilities_details')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('eid_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mosques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eid_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('facilities_details', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('imam_jumua_name')
        batch_op.drop_column('imam_5_prayers_name')
        batch_op.drop_column('muazzin_name')
        batch_op.drop_column('eid_prayer_time')

    with op.batch_alter_table('mosque_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facilities_details', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('imam_jumua_name')
        batch_op.drop_column('imam_5_prayers_name')
        batch_op.drop_column('muazzin_name')
        batch_op.drop_column('iqama_times_json')

    