"""Add image_url column

Revision ID: dbe689cd7e0e
Revises: c7d0d6f2893e
Create Date: 2026-01-15 07:39:52.541527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe689cd7e0e'
down_revision = 'c7d0d6f2893e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mosque_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('mosques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mosques', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('mosque_suggestions', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    
