"""suggestion jumuah/eid + iqama confirm count

Revision ID: fa02001ca36a
Revises: 
Create Date: 2026-01-08 09:28:19.538127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa02001ca36a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mosque_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumuah_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('eid_info', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mosque_suggestions', schema=None) as batch_op:
        batch_op.drop_column('eid_info')
        batch_op.drop_column('jumuah_time')

    # ### end Alembic commands ###
